config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :accounts

  resources :subreddits do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :subreddits
  has_many :posts

  def full_name
    "#{firs_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :subreddit
  validates_presence_of :title, :body, :account_id, :subreddit_id
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  belongs_to :account
  validates_presence_of :url, :name, :rules
  has_many :posts
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :account
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:firs_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firs_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subreddits = Subreddit.all.limit(5)
    @posts = Post.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [ :index, :show, ]
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @subreddit = Subreddit.find(params[:subreddit_id])
    @post = Post.new
  end

  def create
    @post = Post.new post_values
    @post.account_id = current_account.id
    @post.subreddit_id = params[:subreddit_id]

    if @post.save
      redirect_to subreddit_path(@post.subreddit_id)
    else
      @subreddit = Subreddit.find(params[:subreddit_id])
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params[:id])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to post_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_values
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :authenticate_account!, except: [ :index, :show ]
  before_action :set_subreddit, only: [:show]

  def index
    @subreddits = Subreddit.all
  end

  def show
    @posts = @subreddit.posts
  end

  def new
    @subreddit = Subreddit.new
  end

  def create
    @subreddit = Subreddit.new subreddit_values
    @subreddit.account_id = current_account.id

    if @subreddit.save
      redirect_to subreddits_path
    else
      render :new
    end
  end

  private

  def set_subreddit
    @subreddit = Subreddit.find(params[:id])
  end

  def subreddit_values
    params.require(:subreddit).permit(:name, :url, :rules)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row mt-4">
  <div class="col">
    <p class="h5">Popular Posts</p>
  </div>
</div>
  <div class="row">
  <div class="col-8">
      <% @posts.each do |post| %>
      <div class="card p-3">
        <p><small>Subreddit: <%= link_to post.subreddit.name %> Posted by <%= post.account.full_name %> <%= time_ago_in_words post.created_at %> ago.</small></p>
        <h4><%= link_to post.title, subreddit_post_path(post.subreddit_id, post) %></h4>
        <p><%= truncate post.body, length: 200 %></p>
      </div>
      <% end %>
    </div>
  <div class="col-4">
    <p class="h5 mb-4">Popular Subreddits</p>
    <div class="card">
      <ul class="list-group">
        <% @subreddits.each do |subreddit| %>
          <li class="list-group-item"><%= link_to subreddit.name, subreddit_path(subreddit) %></li>
        <% end %>
      </ul>
    </div>
    <%= link_to "View all", subreddits_path, class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3">
      <div class="float-right">
        <% if account_signed_in?  %>
          <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-outline-primary" %>

        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <p class="h3"> <%= link_to "Reddit Clone", root_path %></p>
    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3">
      <div class="float-right">
        <% if account_signed_in?  %>
          <div class="dropdown show">
            <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_account.full_name %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to "Profile", "", class: "dropdown-item" %>
              <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <p class="h3"> <%= link_to "Reddit Clone", root_path %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <section class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-sm-12"></div>
              <%= yield %>
          </div>
        </div>
      </div>
    </section>

    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for [@subreddit, @post] do |form| %>
      <div class="form-group">
        <%= label_tag :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :body %>
        <%= form.text_area :body, class: "form-control" %>
      </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "Back", :back, class: "btn btn-primary" %>
  </div>
</div

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<div>
  <h2>Create new post</h2>
  <div>
      <%= render partial: "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <h2><%= @post.title  %></h2>
  <p> <%= @post.body %></p>
<div>
  <h2><%= @post.title  %></h2>
  <p> <%= @post.body %></p>
  <p>
    edit post button
  </p>
</div>

app/views/subreddits/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @subreddit do |form| %>
      <div class="form-group">
        <%= label_tag :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :url %>
        <%= form.text_field :url, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
      </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div

app/views/subreddits/index.html.erb
<div>
  <% if account_signed_in?  %>
  <div>
    <%= link_to "create new subreddit", new_subreddit_path, class: "btn btn-primary" %>
  </div>
  <div class="card">
  <ul class="list-group">
    <% if @subreddits.size > 0 %>
      <% @subreddits.all.each do |subreddit| %>
        <div class="card">
          <h3><%= link_to subreddit.name, subreddit %></h3>
          <%= simple_format subreddit.rules %>
      <% end %>
    <% else %>
      <p>No subreddits created.</p>
    <% end %>
  </ul>
</div>

<% end %>

</div>

app/views/subreddits/new.html.erb
<%= render partial: "form" %>

app/views/subreddits/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col">
      <h1><%= @subreddit.name %> subreddit</h1>
    </div>
  </div>
    <div class="row">
    <div class="col-8">
      <% @posts.each do |post| %>
        <h4><%= link_to post.title, subreddit_post_path(@subreddit, post) %></h4>
        <p><%= post.body %></p>
      <% end %>
    </div>
    <div class="col-4">
      <p class="h5 mb-4">Subreddit Rules</p>
      <div class="card">
        <ol class="list-group">
          <%= @subreddit.rules %>
        </ol>
      </div>
    </div>
  </div>
  <%= link_to "Create New Post", new_subreddit_post_path(@subreddit), class: "btn btn-primary" %>
</div>